### ISSUE TITLE
new log format?

### ISSUE THREAD

**Issue by action156** [mhanney/zwiftalizer#1]
Hi Mike
great utility. I have just got off the HDR ride and loaded the log, but only got time and date and otherwise a blank screen. Given Zwift had a huge update tonight I thought it may have had a change to the log format - or my computer was just being temperamental
[Log.txt](https://github.com/mhanney/zwiftalizer/files/446922/Log.txt)
. Just FYI just in case.
cheers
Stephen

**Comment by mhanney** [comment]
Thanks Stephen, that's unfortunate. I am away from my computer this week so will fix it in a week or so. 
Mike



		_____________________________

**Comment by action156** [comment]
All good Mike. Tried again this morning and same outcome!  Something had
changed. Enjoy your travels.
Cheers
Stephen

**Comment by mhanney** [comment]
This is now resolved. The log format hasn't changed (luckily). There are a now a lot of entries about updated WAD and texture files that come before the CPU and GPU entries. For speed, when grepping out the CPU and GPU entries, I was only readying the first 16 KB of the file (or whole thing if total KB < 16) , which is no longer enough. The resolution was simple - increase the chunk to 64 KB. This could change again. The safe thing to do would be to read the whole thing, but all those regexes are starting to get quite slow on old CPUs.

**Comment by action156** [comment]
Nice job. Thanks.
