### ISSUE TITLE
more than one 'goto search' reported when only one is expected

### ISSUE THREAD

**Issue by mhanney** [mhanney/zwiftalizer#11]
Is there something other than “goto search” that you count as a search? My latest ride only has one search in the logs but shows two on Zwiftalizer.

**Comment by kylemacfarlane** [comment]
The extra one is always right at the start so I thought maybe you put it there on purpose.

**Comment by mhanney** [comment]
I just looked at my code. I count 'goto search' AND 'ant usb receiver found'.

https://github.com/mhanney/zwiftalizer/blob/master/src/parser/mapAntSearches.js line 20

**Comment by kylemacfarlane** [comment]
`ANT USB receiver found` only seems to appear once at the start of the log. Even unplugging and replugging the dongle doesn't make it reappear.

What seems to be the real signature of a replug is:

> ANT  : TX POWER ID
> ANT  : RESET Complete, reason: 
> ANT  : RESET_POR

These could be useful to log as they could mean a USB port power problem or a loose cable.

While doing all this unplugging/replugging it one time triggered thousands of these:

> ANT  : Could not assign channel 0 to network 0
> ANT  : Could not assign channel 0 to network 1

If these are appearing then Zwift will see the dongle as connected but won't find anything to pair to. To fix this you have unplug/replug again. This is the same bug I would often see with the Tacx T2028.

**Comment by mhanney** [comment]
I have updated my code to count  'goto search' AND 'TX POWER ID' lines as device searches.
