### ISSUE TITLE
Investigate if its necessary to assume some devices are sampled at 8HZ, or if we can always use 4HZ

### ISSUE THREAD

**Issue by mhanney** [mhanney/zwiftalizer#12]
> I signed up for an ANT+ Adopter account to access the PDFs and get Hz info.
> 
> Heart rate = 4Hz with an optional background page every 1/65th containing battery level etc
> Speed = 4Hz with an optional background page every 1/65th
> Cadence = 4Hz with an optional background page every 1/65th
> Speed + Cadence = 8Hz no background pages
> Power = 4Hz with optional 8Hz advanced capabilities
> FE-C = 4Hz with optional 8Hz advanced capabilities
> Assuming nobody would pair a speed + cadence sensor to Zwift, I take this to mean you should always assume 4Hz unless you see things like power, torque, revs, etc in the logs in which case it must be 8Hz. Could be wrong though.

**Comment by mhanney** [comment]
"Assuming nobody would pair a speed + cadence sensor to Zwift"

Zpower users pair speed and cadence sensors. I would like to support those too.

My Garmin cadence sensor is also a speed sensor, and I have a supported trainer - Kurt Road Machine - with THE most accurate power curve estimation - so I can use it to make a test log. I've been meaning to do this for over a year but never go 'round to it.

**Comment by mhanney** [comment]
Kickr works in two modes - the ANT+ power meter profile and a proprietary ANT+ gradient change profile for their resistance change messages - which uses the advanced capabilities at 8HZ, I believe. And it works in a FE-C mode, which I think is the ANT+ power meter profile again, with a variation on the FE-C gradient profile, also at 8HZ. I don't have one anymore so might be difficult to test.

My PowerTap hub does show revs, torque, power, and even calibration data, so I think I definitely have to assume power meters and some smart trainers are sampled at 8HZ. I will keep this issue open anyway because I want to NOT assume anything, and use the new device type lookup data to decide.

**Comment by kylemacfarlane** [comment]
The KICKR is something I noticed in ZwiftApp.exe. There appears to be a bunch of custom KICKR strings so I assume these would show up in the log?

> KICKR: Detected wrong state
> KICKR: Will try to re-set SIM mode
> KICKR: no controllable trainer paired
> Unknown wahoo data page 240 [%d] [%d] [%d] [%d] [%d] [%d] [%d]
> KICKR: will wait a bit longer before trying to re-set SIM mode
> KICKR: no controllable trainer component
> KICKR queuing Grade to %1.1f
> KICKR queuing Grade to %1.1f via burst
> KICKR queuing ERG to %d
> KICKR queuing ERG to %d via burst
> KICKR changing ERG to %3.2f
> KICKR changing grade to %3.2f
> WAHOO KICKR
> WAHOO KICKR %d
> KICKR ANT Transfer in error
> KICKR Transfer sequence error.
> KICKR Transmission failed. Retrying command
> KICKR grade set successfully
> KICKR queuing grade change to %3.2f
> KICKR changing wind speed to %3.2f
> KICKR command sending...
> KICKR ANT Transfer already in progress
> KICKR switching to new broadcast style messages
> KICKR Setting Sim Mode
> KICKR wind set successfully
> KICKR simluation mode set successfully
> KICKR erg mode set successfully
> KICKR unhandled event %d
> BLEM: KICKR queuing grade change to %3.2f

I think they might have tried to implement calibration in Zwift at one point:

> Calibration data [%d] [%d] [%d] [%d] [%d] [%d] [%d] [%d]
> NEW Calibration offset = %d stdDeviation = %3.2f
> ******************   FAILED Calibration offset = %3.2f stdDeviation = %3.2f

**Comment by mhanney** [comment]
I've always wondered why they are logging the calibration data. A user in the Facebook Zwift Coders group told me it is so they can tell if a user has manually adjusted the slope - power meter doping. That Deviation could be how far away the current value is from from the expected value for that model. However, it's an arbitrary number for each individual device based on how it was really calibrated (not just tared or zero offset) when it left the factory.

The PMs with user serviceable slopes are Quark and SRM, and possibly one or two other high end ones. 

Also, unrelated, 4iiii left only power meter is easy to 'dope' because its phone app allows the user to set a left / right leg imbalance %, which can be set positive to inflate the left leg, inflating the overall power reading by up to 10%.

**Comment by mhanney** [comment]
How do you get the strings out of the Zwift.exe ? Just curious incase the BTLE protocol knows anything about Kurt smart trainers. I would really like to include that brand in the new report. Their chief of marketing actually emailed me this week to ask if there's anything I need from them. Pretty cool. I've asked for example logs.

**Comment by kylemacfarlane** [comment]
I used Process Explorer but here's a copy of the list sorted alphabetically: https://gist.github.com/kylemacfarlane/29a1b6cb872d3e4f9fdab90f49eb40a1

**Comment by mhanney** [comment]
I decode the calibration data, if present, and show it under the device heading in the ANT+ chart.
One of the two numbers should be the same as what the user is used to seeing on their head unit (Garmin or whatever).
There are two numbers because some manufacturers use lowest bit first, and others use highest bit first. 
That is probably when I got the most into reading the ANT+ spec.

**Comment by kylemacfarlane** [comment]
Also here it is in the order Process Explorer dumped it: https://gist.github.com/kylemacfarlane/4405ce5dffaac4d203fae1b1735b4bf1

This can be useful because the strings are closer to the order they appear in the code which can make it easier to guess what might be going on.

For example near some of the KICKR strings you can see there are also a lot of strings for FET, ELITE, and SARIS.

**Comment by mhanney** [comment]
That's amazing. I think I can see what I need to get Kinetic into the smart trainers survey. It'll work for now because they only have one smart resistance unit, and it's the only one that does BTLE and not ANT+. That might be a bit risky actually. I will not know the manufacturer Id or model Id, because that is not logged when devices are paired using BTLE, and I can only do it if I can tell the difference between the smart resistance unit and the InRide sensor. I'm expecting to get logs from Kinetic engineering soon. On the other hand, I might not, because it will complicate explaining how the survey is made if I say 'only ant+ devices are included, and Kinetic'.

Thinking aloud, there's enough difference in the BLEM messages to do a whole new section of the power sources survey - BTLE paired trainers - no models, just the following KICRK, TACX, KINETIC, SARIS, ELITE

**Comment by kylemacfarlane** [comment]
Llama's logs have huge amounts of Rx fails. Literally every second there are four Rx fails yet no "goto search" or activity on channel 0. Thus his devices must be operating at 8Hz.

It makes for an interesting comparison though.

Llama's Drivo:
- 55% "page loss" on trainer (Rx fails)
- 18% "page loss" on other sensors (Rx fails)
- 2 goto searches (resyncs)
- Some channel 0 activity (radio searches)

Llama's Quarq:
- 53% "page loss" on trainer
- 0.9% "page loss" on other sensors (how is this one so low?)
- No goto searches
- No channel 0 activity beyond start

Llama's Quarq 2.
- 62% "page loss" on trainer
- No other sensors
- 1 goto search
- No channel 0 activity beyond start

My Bushido Smart:
- 15% "page loss" on trainer
- 7% "page loss" on other sensors
- 0-1 goto searches per hour (depends on what Bluetooth headphones I'm using)
- No channel 0 activity beyond start

My guess is Lama's environment is very bad but his equipment is very good so is managing to hang on.

**Comment by mhanney** [comment]
I just want to clarify a few things...

The Drivo, Hammer and Quarq logs aren't Shane's. 

The Drivo and Hammer logs were made up just for testing - they are copies of the Tacx Neo log with manufacturer Id and model Id changed.

The Quarq logs are real, but are very old.

**Comment by mhanney** [comment]
I've just pushed an update that uses 8HZ for power meters, Kickr & Neo & devices where max RxFails in 1 second is 8, else use 4HZ.

**Comment by kylemacfarlane** [comment]
For my script I went with >5 rx fails in the same second means 8Hz.

**Comment by Landixus** [comment]
I have the experience that on 4Hz i have much drop outs ( 50%)
With 8 HZ i have only drop outs (1 %)
Channel period Data is transmitted from most bike power sensors every 8192/32768 seconds (4Hz)
If somebody can test and confirm this, too? So 8Hz is the better choice

**Comment by mhanney** [comment]
The 2017-06-14 London Course Expansion update appears to have changed the power meter device pairing to use a data rate of 4Hz.  Some Kickrs still use 8Hz. It is likely that there was a code change to set the data rate according to device type instead of setting all power meters at 8Hz. 

See the ANT+ Info thread for Chip Hawkins' (Wahoo CEO) comments on why power meters might have been set at 8Hz in the first place when almost all are 4Hz devices. https://github.com/mhanney/zwiftalizer/issues/10
