### ISSUE TITLE
As a user, I want to see the actual vs expected theoretical max signals per hour for my device, so that I can see at a glance if I have a signal strength issue caused by environmental factors.

### ISSUE THREAD

**Issue by mhanney** [mhanney/zwiftalizer#15]
> Now that you're keeping track of what trainers and power meters people use would it be possible for Zwiftalizer to keep track of something like "median Rx fails per hour per user" for each device? This would give people an indication of whether any problems they have is their environment or just the best their device can do.

**Comment by mhanney** [comment]
That is a fantastic suggestion Kyle. I hope I captured the use case correctly in the title of this feature request. I will definitely give this some thought and see if it is something I can store in the db without my costs ballooning. 

I really like it because many users do not understand all the numbers and have asked for simply - marks out of 10. 

I did that with the system specs, very, very quickly, and somewhat whimsically. Most people understand that it is just a bit a fun (including DC Rainmaker - DCR57 podcast) :-) and some people took it quite seriously, but over all - I do actually think it has merit for those who are really into the graphics performance.

For the ANT+ signal I would take it much, much more seriously because I know how annoying it is to experience a drop out in a virtual race. And I know a lot of people who race use the tool. I think the ANT+ signal plot is becoming a more useful feature than the graphics stats. It has a lot of room for improvement.

**Comment by kylemacfarlane** [comment]
One problem with purely taking some kind of average is that I imagine most players have a crap setup and players drawn to troubleshooting their logs have an even crapper setup. Even when you watch races it's not unusual for a top rider to have a drop out which really shouldn't be happening unless something uncontrollable like a police helicopter flies over.

Would it also be worth putting together some of the ANT+ troubleshooting I went through into a wiki on here? I'm no expert (hence an easily editable wiki) but I can go into more detail than what's easily available right now. I already mentioned channel 10 over on Zwiftblog but also buying a new 5Ghz router will most likely make no difference or even make things worse. Instead it would be better advice to buy a router that allows you to adjust the transmit power.

I haven't seen anyone mention the fact that USB 3.0 operating at high speed (meaning external hard drives, etc) can interfere with Bluetooth which probably also means ANT:

- http://www.intel.com/content/www/us/en/io/universal-serial-bus/usb3-frequency-interference-paper.html
- https://support.apple.com/en-gb/HT203729

Tacx told me not use extension cables over 1.5m (I still use a 2m one) as the benefit of getting away from the computer is reduced by the longer cable picking up noise. Even the official Zwift extension cable is 10ft/3m long and unless it's shielded or something (probably not for $5) I doubt it helps anyone.

**Comment by mhanney** [comment]
I agree with that - if only users with ANT+ problems use the tool then a lot of the data collected would be from messy set-ups. I do find it a bit surprising when top racers get drop outs. I never have any.

I'll remove the 5 ghz router idea on your recommendation. My 2.4 is a dirt cheap linksys that I flashed with dd-wrt, so that I could increase the transmit power actually.

I do think it would be very, very useful to start a wiki. The info on kb.zwiftriders.com and older zwiftblog posts is detailed, long and technical, and perhaps over most people's heads.  Writing technical information for a largely non-technical crowd is something I find very difficult.  Lama's passion for this subject is fantastic and he's a brilliant communicator - great at distilling the technical details for the public. I don't have that talent. I find it really hard to keep it short. I wrote my bullet points based on what I remembered from his toubleshooting video, but didn't want to copy it verbatim, because, well, it's his thing isn't it. He does recommend an extension cable, and I think I can guess why - because for many people it will fix their issue and it's an easy thing for a non-tech person to do, and time is people's most valuable asset. Asking a recreational cyclist to open their router's admin page and configure channels over the phone is just not a good use of time. I think he does at least make make a point of getting a powered one. But like D.A.D often says - an extension cable is a band aid masking the real issue. 

I debated not even giving any tips at all, because as soon as I do, I'm on the hook for support, but if someone is using the tool because they have an issue, then it makes sense at least have something there.

Lastly, I don't ever want to do anything that would cause a headache for official Zwift tech support - I can envisage a conversation where a user raises a ticket, or calls in, because they want help with something I recommended on my site. There is already confusion about who is behind zwiftpower.com, zwiftblog.com and sometime, but not very often, what I am doing.

**Comment by kylemacfarlane** [comment]
An extension cable is absolutely necessary and despite all the talk about WiFi etc I think the number one source of interference is your computer. It's why I also suspect that it might be a bad idea to put the ANT+ dongle too close to the trainer as surely they are outputting noise as well. 

The length and manufacturer of a cable also matters. 3m cables did absolutely nothing for me and a 2m Amazon Basic cable didn't do much either. It's only after I solved DispalyPort problems with Lindy 3m cables that I also tried Lindy USB cables and they solved it for me.

You actually would want to turn down the transmit power on your router. Generally speaking multiple low power access points are better than one high power AP. The problem is consumer APs tend to all turn the power up to max to win at benchmarks but it's actually pointless because most mobile devices can't reply to the signal at long range and it prevents them from connecting to closer APs. So basically all these consumer APs do is interfere with everything.

In regards to 5GHz it's mostly intended to be used in a single room like classrooms and will not make it through many walls. So a 5GHz router will fall back to 2.4GHz unless  you're nearby. The reason I said it might make it worse is back to the original point that consumer routers tend to keep cranking up the power so a new router might have an even stronger 2.4GHz signal than the old one. Of course you could turn off the 2.4GHz radio and be 100% 5GHz but then you'd have terrible range and older devices won't be able to connect.

**Comment by kylemacfarlane** [comment]
The reason an extension cable is needed is that the antennas keep getting smaller. Check out the difference between these:

- ANTUSB2: https://fccid.io/document.php?id=1270177
- ANTUSB-m: https://fccid.io/document.php?id=1876331
- Suunto: https://fccid.io/document.php?id=1451027

With the older ANTUSB2 there is a big antenna on the end but with the other two I'm pretty sure it's those zig zag tracks on the opposite side of the USB connector: https://en.wikipedia.org/wiki/Inverted-F_antenna. The antenna is literally inside the USB port!

This is why I think the Suunto is the worst ANT+ dongle.

- ANTUSB-m = pairs super fast which we now know is down to High Duty Searching
- Tacx T2028 = has a built in extension cable (I had other problems with it though)
- ANTUSB2 = aerial is outside of port
- Suunto = no advantages

**Comment by mhanney** [comment]
Wow. Yes, looks like the mini dongle antenna is either inside the port, or if it's sticking out a tiny bit it's perpendicular to the metal PC chassis. I must just be lucky that I do not need an extension cable with my Suunto, PowerTap, cadence and hr sensors - about 6 feet from the PC with no other equipment nearby.

**Comment by kylemacfarlane** [comment]
What case do you have? Could be something to do with how your ports are attached to the case?

**Comment by mhanney** [comment]
Could very well be. My Zwift PC case is a crappy Gateway that I pulled out of a recycling bin. The USB ports are in a plastic moulding at the top front lip, like this one http://www.gateway.com/gw/en/US/content/dx-series/dx-series

**Comment by mhanney** [comment]
I did some work on this today but didn't have a lot of time.  So far, I've just added the data rate and % of RxFails alongside each chart. It's live. 

I also did a few zwift sessions using a 12 inch high quality extension cable, which puts the dongle just behind my front brake. The % fail rate was probably the lowest I've ever had. I used a Suunto and Anself ($8.99 ebay) mini dongle and results were pretty much identical. Probably identical chips inside.

**Comment by mhanney** [comment]
Kyle, would it be ok with you if I start a wiki here to document your findings, and change the Zwiftalizer tips based on it? I'd credit you of course, but I'm afraid I can only offer kudos as I have no money and the site makes next to nothing.

**Comment by kylemacfarlane** [comment]
Yeah a Wiki is fine but it seems to me that it really comes down to getting the dongle away from your PC without using a cable that creates its own problems by being too long or low quality. On the other hand in a completely different environment maybe other things do matter.

I never saw a difference in dongles in terms of actual fails. The difference was only how quickly they would reconnect after a drop.

Our average fails are slightly different per log (e.g. 13.48% vs 13.28%) but that's probably due to how I put the results into 10s bins. 

I emailed Tacx and Wahoo about the 100s thing. Tacx said they passed it along and Wahoo haven't replied yet.

**Comment by mhanney** [comment]
I went with % of RxFails over total time. 

My current bucket size is 3s average RxFails.

The max zoom size is also 3s.

**Comment by kylemacfarlane** [comment]
Is this live on zwiftalizer.com? I can't see anywhere to compare rx fails with other users.

In the release notes for the latest version of Zwift they say that the pedestrians are currently just a test to see how they affect FPS. If Zwift is going to continue to add more detail then would it be a good idea for Zwiftalizer to segment performance by Zwift version?

**Comment by mhanney** [comment]
No. I have not done anything yet to store rx fails per device per user to make comparisons. I don't have any free time at the moment.

Yes. It would be a good idea to segment graphics performance by zwift version. I've thought about that each time there is a major update. Performance has improved a lot with each release, especially after the iOS release - they optimized all the models I think.  I can't remember if version is in the log file. It probably is, but I haven't stored it. I could do it roughly by log date, when I have time. That wouldn't be very difficult. It's time consuming though.

I might do the simplest thing that works - start saving version now, and dump everything that came before into the same pile. I think it would be great to have fewer items in the benchmarks report anyway.
