### ISSUE TITLE
Log file fails to complete -- Error: TimeSeries was passed non-chronological events

### ISSUE THREAD

**Issue by toppie-c** [mhanney/zwiftalizer#16]
I've had a few log files that fail to complete recently. This is the first I've looked further into.  After dragging the file, the browser just stays at the "Reading file" with the circle spinning.  The browser debugger (chrome and firefox) shows: "Error: TimeSeries was passed non-chronological events".  I cloned the repo to see if I could see what is offensive in the zwift log file, but 'npm run dev' I get an error from antManufacturers.js where it can't resolve the file referenced in "const AntplusDevices = require('../../local_modules/node_modules/zwiftalizer-antplus-devices');"   Setup: Mac, GarminUSB receiver, Kickr(gen1), Vector2, Garmin HRM.  Thanks, TC
[Log_w_big_resistance_at_44m.txt](https://github.com/mhanney/zwiftalizer/files/1034619/Log_w_big_resistance_at_44m.txt)

**Comment by mhanney** [comment]
I just got that error myself today. I will be looking at it tonight.

For the npm dependencies, clone zwiftalizer-antplus-devices in the same dir that you cloned zwiftalizer and run npm run install-local-modules.

 I'll publish that to npm soon, after the json lookup of devices is a bit more complete, and tidied up.

 I didn't expect anyone to clone it, but that's awesome. Pull requests would be gratefully received.

The master branch is a bit in flux today actually- I started something then had to bail and come back to it later at a different location.


________________________________

**Comment by toppie-c** [comment]
From the log file I attached:
[7:45:29] FPS  35, -103934, 10237, 92044
[7:45:32] FPS  35, -107141, 10199, 89567
**[7:45:31] FPS  32, -110487, 10178, 87204**
[7:45:35] FPS  32, -109561, 10108, 83451

It looks like time went backward for a bit.
[7:45:34] FE-C 26 received^M
[7:45:34] Unknown power data [226] [119] [63] [83] [4] [254] [255] [255]^M
[7:45:34] Unknown power data [224] [119] [243] [136] [48] [83] [226] [1]^M
[7:45:35] Unknown power data [225] [114] [2] [136] [54] [79] [20] [2]^M
**[7:45:31] FPS  32, -110487, 10178, 87204^M**
[7:45:31] Unknown power data [19] [120] [183] [173] [43] [53] [255] [255]^M
[7:45:32] FE-C 26 received^M
[7:45:32] ANT  : Transfer Completed.^M
[7:45:32] ANT  : dID 755406 Battery Level 3^M

**Comment by toppie-c** [comment]
Looking at the system log, it appears as though system time was adjusted backwards by 4 seconds at that time.  I'll guess by NTP, but I didn't have ntpd logging on, so can't tell.

**Comment by mhanney** [comment]
This could just be a weird coincidence, but exactly the same thing happened to me today. 

I also use an ntp server to set the time. 26 seconds shift is huge. Could be correct though. I only use this machine for Zwift, and it's in sleep mode except for a hand full of hours a week.

[14:48:14] FPS 149, 619866, 11088, -86570
[14:48:15] ANT  : Rx Fail on channel 3
[14:48:15] ANT  : [PowerMeter] Prev: WheelPower: EC: 163  WT: 148  Period: 01003  AccumTorque: 19707
[14:48:15] ANT  : [PowerMeter] WheelPower: EC: 164  WT: 150  Period: 01867  AccumTorque: 19934
[14:48:15] ANT  : [PowerMeter] Vang = 14.89 radians/sec   Tavg: 7.09 nm   Pavg: 105.65 watts timeElapsed=0.422
**[14:47:49] ANT  : Rx Fail on channel 3**
[14:47:49] FPS 149, 619601, 11096, -86661
[14:47:49] ANT  : Rx Fail on channel 3
[14:47:50] ANT  : Rx Fail on channel 3
[14:47:50] ANT  : Rx Fail on channel 3
[14:47:50] FPS 150, 619340, 11102, -86739
[14:47:50] ANT  : [PowerMeter] Prev: WheelPower: EC: 164  WT: 150  Period: 01867  AccumTorque: 19934
[14:47:50] ANT  : [PowerMeter] WheelPower: EC: 165  WT: 153  Period: 02727  AccumTorque: 20201
[14:47:50] ANT  : [PowerMeter] Vang = 14.96 radians/sec   Tavg: 8.34 nm   Pavg: 124.84 watts timeElapsed=0.420

I'll have to add a check to skip any lines where the time is less than the previous time.

I should also put the whole log reading part in a try catch. Hanging on the spinning wheel is a bit crap really.

**Comment by toppie-c** [comment]
My laptop is usually in sleep mode for 6-12 hours just before use with zwift.  I'll figure out how to get ntpd to log and see if this happens again.  I'll also look through old log files to see if I still have any others that wouldn't complete, and if they show the same dateTime issue.

I hacked a quick change to epochify.js that assumes that if dateTime goes backwards, that the current unixtimestamp stays the same as the previous, and fixes up all timestamps from that point on.  This might lose some time, but it at least keeps the timestamps in increasing order.  It was sufficient to get my log to display output (which showed much better signal levels with the Kickr using FE-C and the Vector2 as the power source, than with the Kickr being the power source--some periodic dips, but none to a level of zero).

```
diff --git a/src/parser/epochify.js b/src/parser/epochify.js
index 96513a3..575047c 100644
--- a/src/parser/epochify.js
+++ b/src/parser/epochify.js
@@ -35,6 +35,8 @@ export default async function epochify(str, callback) {
   //let logDayFormatted = logDay.format(ansiDateFormat)
   let logDayFormatted = logDay.format(slashDateFormat);
 
+  let fudgeTime = 0;
+
   const convertAll = function() {
     var lines = [];
 
@@ -83,7 +85,15 @@ export default async function epochify(str, callback) {
       if (previousTime.dateTime && previousTime.dateTime === dateTime) {
         lines.push('[' + previousTime.unixtimestamp + '] ' + value);
       } else {
-        const unixtimestamp = Date.parse(dateTime);
+        let unixtimestamp = Date.parse(dateTime) + fudgeTime;
+        if (unixtimestamp < previousTime.unixtimestamp) {
+          // time went backwards.  Even thought it went backwards, assume that it hasn't
+          // progressed further than the last dateTime (we don't really know if it has)
+          // e.g. if was 1:23:45, and now shows 1:23:41, consider unixtimestamp to be 
+          // that of 1:23:45, and set fudgeTime so that all future timestamps are corrected.
+          fudgeTime = previousTime.unixtimestamp - unixtimestamp;
+          unixtimestamp = previousTime.unixtimestamp;
+        }
         lines.push('[' + unixtimestamp + '] ' + value);
         previousTime.dateTime = dateTime;
         previousTime.unixtimestamp = unixtimestamp;

```

**Comment by mhanney** [comment]
Ah crap. I just pushed a similar fix before seeing yours. Mine's a bit brutal by comparison - it drops lines until the time is back to being chronological. 

Incidentally, I've recently switched from Atom to VSCode with Prettier and Eslint plug-ins, which is why when I touch any old code it gets reformatted, like those string concat lines which are now templated strings. Oh, and the Date.parse(dateTime) in this loop was a major performance hot spot in the whole thing, which is why I check the string version of the dateTime with the previous one first. Looks weird looking back at it now.

**Comment by toppie-c** [comment]
I'm good with any fix.  Just so you know, my background is embedded C/C++ for network devices, so anything with a UI is mostly unfamiliar territory for me--I had to google Atom, VSCode, Prettier and Eslint.  I figured, if you made it open source, I might as well take a look to see if I can figure out what is going on--thinking it was something very specific to my setup which I've had issues with recently.  BTW, zwiftalizer has helped immensely with working through these issues.  I think I have things working well now, but there have been days where I would have preferred a direct USB connection between laptop and trainer.

**Comment by mhanney** [comment]
That's great to hear. I know a couple of guys in my neighbourhood who use the CompuTrainer, which has a hard USB connection They never have any problems. Kinetic's smart trainer head also has a USB connection, I think, and BTLE, but no ANT+.

Any C/C++ devloper must think the current JavaScript ecosystem is a complete cluser F, and you'd be right. It's rubbish.
