### ISSUE TITLE
Error received when uploading my zwift log

### ISSUE THREAD

**Issue by dom356** [mhanney/zwiftalizer#21]
[Log.txt](https://github.com/mhanney/zwiftalizer/files/1171636/Log.txt)

Please find attached log file from my zwift system that threw an error while trying to upload to zwiftalizer. Please let me know if you need anything else from me.

Regards,
Dom

**Comment by mhanney** [comment]
Hi Dom,

Thanks for attaching your log.txt. I wasn't able to reproduce any error. The log is very short. Are you sure this is the one that threw the error?

**Comment by dom356** [comment]
Hi Mike, yes I'm pretty sure that's the log. However I installed Chrome and was then able to upload the file. The original problem was in Internet Explorer 11. When I get back on my laptop I will send the exact log file direct to you just to make sure it is the correct file, but as it loaded correctly through Chrome, I don't think it's the file, but something in IE 11 causing the problem.

Cheers,
Dom

**Comment by mhanney** [comment]
I should've asked which browser. I will take a look in Internet Explorer 11 tonight (I'm doing some maintenance to update the dependencies over on the unstable branch). My google analytics show fewer than 2.5% of users use IE11, so to be honest, I don't test on it. The top 3 are Chrome (55.55%), Safari (19.69%) and Edge (8.33%), with Firefox a close 4th (8.29%) in the last 6 months.

**Comment by mhanney** [comment]
IE11 is now supported & tested.
